### ISSUE TITLE
Error when setting unusual frame rates

### ISSUE THREAD

**Issue by DeinAlptraum** [HansiMcKlaus/AudioSpectrumVisualizer#3]
When setting the `-fr` flag to "unusual" values, the script crashes with an error, see for example:

```
~ >>> asv ~/DataShare/Video-Audio/Music/Arctic\ Monkeys\ -\ Do\ I\ Wanna\ Know\ \(Official\ Video\).mp3 ~/Desktop/testboi -e 20 -fr 18
Audio succesfully loaded. (1/4)
Traceback (most recent call last):
  File "/home/deinalptraum/DataShare/Programming/repos/AudioSpectrumVisualizer/AudioSpectrumVisualizer.py", line 329, in <module>
    full()
  File "/home/deinalptraum/DataShare/Programming/repos/AudioSpectrumVisualizer/AudioSpectrumVisualizer.py", line 297, in full
    frameData = calculateFrameData(fileData, samplerate)
  File "/home/deinalptraum/DataShare/Programming/repos/AudioSpectrumVisualizer/AudioSpectrumVisualizer.py", line 73, in calculateFrameData
    lastFrame[0:len(currentFrameData)] = currentFrameData
ValueError: could not broadcast input array from shape (2667,) into shape (2666,)
```

I have observed this on a 20 second with framerates 17, 18 and 31 so far.

**Comment by HansiMcKlaus** [comment]
Fixed in 6cb178f519a9a7f53d3b6567ba51239da78bea72
